Vagrant.configure("2") do |config|
  config.vm.define "vsrx" do |v|
    v.vm.box = "juniper/ffp-12.1X47-D15.4-packetmode"
    v.vm.network "private_network", virtualbox__intnet: "my-network"
    v.ssh.insert_key = false
  end
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
end
