Vagrant.configure("2") do |config|
  config.vm.define "node-1" do |n1|
    n1.vm.box = "almalinux/9"
    n1.vm.network "forwarded_port", guest: 80, host: 8080
    n1.vm.network "private_network", ip: "192.168.33.2"
    n1.vm.hostname = "node-1"
  end

  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = "2048"
    v.vmx["numvcpus"] = "2"
  end

end
