Vagrant.configure("2") do |config|
  config.vm.define "node-1" do |n1|
    n1.vm.box = "almalinux/9"
    n1.vm.network "private_network", ip: "192.168.33.2", virtualbox__intnet: "intnet"
    n1.vm.network "private_network", type: "dhcp",virtualbox__intnet: "my-network"
    n1.vm.hostname = "node-1"
  end

  config.vm.define "node-2" do |n2|
    n2.vm.box = "almalinux/9"
    n2.vm.network "private_network", ip: "192.168.33.3", virtualbox__intnet: "intnet"
    n2.vm.network "private_network", type: "dhcp",virtualbox__intnet: "my-network"
    n2.vm.hostname = "node-2"
  end

  config.vm.define "node-3" do |n3|
    n3.vm.box = "almalinux/9"
    n3.vm.network "private_network", ip: "192.168.33.4", virtualbox__intnet: "intnet"
    n3.vm.network "private_network", type: "dhcp", virtualbox__intnet: "my-network"
    n3.vm.hostname = "node-3"
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
end
