Vagrant.configure("2") do |config|
  config.vm.define "node-1" do |n1|
    n1.vm.box = "almalinux/9"
    n1.vm.network "private_network", ip: "192.168.33.2"
    n1.vm.hostname = "node-1"
  end

  config.vm.define "node-2" do |n2|
    n2.vm.box = "almalinux/9"
    n2.vm.network "private_network", ip: "192.168.33.3"
    n2.vm.hostname = "node-2"
  end

  config.vm.define "node-3" do |n3|
    n3.vm.box = "almalinux/9"
    n3.vm.network "private_network", ip: "192.168.33.4"
    n3.vm.hostname = "node-3"
  end

  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = "2048"
    v.vmx["numvcpus"] = "2"
  end

end
